version: '3'
services:
  envoy:
    image: envoyproxy/envoy-dev
    working_dir: /envoy
    command:
    - -c
    - envoy.yaml
    - --component-log-level
    - wasm:debug
    - -l
    - warning
    ports:
    - "18000:18000"
    - "8001:8001"
    volumes:
    - .:/envoy
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
