name: CI

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: tinygo/tinygo:0.23.0
    steps:
      - uses: actions/checkout@v2

      - name: Install make
        run: apt-get install make -y

      - name: Build
        run: make build-all

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: go-mod-${{ hashFiles('go.sum') }}

      - name: Test
        run: make test
